"""Neural TTS sidecar for the Bangladesh Betar admin portal (M31).

POST /synthesize {text, language: en|bn, voice: male|female} -> WAV bytes.
Everything runs on onnxruntime — Piper-class lightweight, no PyTorch:
  English — Piper (Ryan / Amy).
  Bangla  — BanglaTTS male / female VITS voices (real Bangladeshi speakers),
            exported to ONNX at build time; tokenization follows the vocab
            JSON generated by Coqui itself during conversion.
"""

import io
import json
import re
import wave

import numpy as np
import onnxruntime
from fastapi import FastAPI, HTTPException
from fastapi.responses import Response
from piper import PiperVoice
from pydantic import BaseModel

app = FastAPI()

EN_VOICES = {
    "male": PiperVoice.load("/models/en_US-ryan-medium.onnx", config_path="/models/en_US-ryan-medium.onnx.json"),
    "female": PiperVoice.load("/models/en_US-amy-medium.onnx", config_path="/models/en_US-amy-medium.onnx.json"),
}


class BanglaVoice:
    """ONNX VITS voice with the tokenizer recipe recorded at conversion time."""

    def __init__(self, onnx_path: str, meta_path: str):
        self.session = onnxruntime.InferenceSession(onnx_path, providers=["CPUExecutionProvider"])
        with open(meta_path, encoding="utf-8") as fh:
            meta = json.load(fh)
        self.table = {c: i for i, c in enumerate(meta["vocab"])}
        self.add_blank = meta["add_blank"]
        self.use_eos_bos = meta["use_eos_bos"]
        self.blank_id = meta["blank_id"]
        self.bos_id = meta["bos_id"]
        self.eos_id = meta["eos_id"]
        self.rate = meta["sample_rate"]
        self.input_names = meta["input_names"]

    def _ids(self, text: str) -> list[int]:
        ids = [self.table[c] for c in text if c in self.table]
        if not ids:
            return []
        if self.add_blank:
            out = [self.blank_id]
            for i in ids:
                out.extend((i, self.blank_id))
            ids = out
        if self.use_eos_bos:
            ids = [self.bos_id, *ids, self.eos_id]
        return ids

    def tts(self, text: str) -> np.ndarray | None:
        ids = self._ids(text)
        if not ids:
            return None
        x = np.array([ids], dtype=np.int64)
        feeds = {}
        for name in self.input_names:
            if name == "input":
                feeds[name] = x
            elif name == "input_lengths":
                feeds[name] = np.array([x.shape[1]], dtype=np.int64)
            elif name == "scales":
                feeds[name] = np.array([0.667, 1.0, 0.8], dtype=np.float32)
        return self.session.run(None, feeds)[0].squeeze().astype(np.float32)


BN_VOICES = {
    "male": BanglaVoice("/models/bn_male.onnx", "/models/bn_male.json"),
    "female": BanglaVoice("/models/bn_female.onnx", "/models/bn_female.json"),
}


class SynthesizeRequest(BaseModel):
    text: str
    language: str  # en | bn
    voice: str = "female"  # male | female


def sentence_chunks(text: str, limit: int = 400):
    """Split on sentence boundaries (Bangla danda included), pack to <= limit chars."""
    parts = re.split(r"(?<=[।.!?\n])\s+", text)
    buf = ""
    for part in parts:
        part = part.strip()
        if not part:
            continue
        if buf and len(buf) + len(part) + 1 > limit:
            yield buf
            buf = part
        else:
            buf = f"{buf} {part}".strip()
    if buf:
        yield buf


def to_wav_bytes(samples: np.ndarray, rate: int) -> bytes:
    peak = float(np.max(np.abs(samples))) if samples.size else 0.0
    if peak > 1.0:  # VITS output can exceed [-1, 1] slightly — normalise
        samples = samples / peak
    pcm = (np.clip(samples, -1.0, 1.0) * 32767).astype(np.int16)
    out = io.BytesIO()
    with wave.open(out, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(pcm.tobytes())
    return out.getvalue()


@app.get("/health")
def health():
    return {"ok": True, "engines": {"en": "piper (ryan/amy)", "bn": "banglatts-onnx (real male/female)"}}


@app.post("/synthesize")
def synthesize(req: SynthesizeRequest):
    text = req.text.strip()
    if not text:
        raise HTTPException(422, "Empty text.")
    voice_key = "male" if req.voice == "male" else "female"

    if req.language == "bn":
        voice = BN_VOICES[voice_key]
        pieces = []
        gap = np.zeros(int(voice.rate * 0.25), dtype=np.float32)
        for chunk in sentence_chunks(text):
            waveform = voice.tts(chunk)
            if waveform is not None and waveform.size:
                pieces.extend((waveform, gap))
        if not pieces:
            raise HTTPException(422, "Nothing to synthesize.")
        return Response(content=to_wav_bytes(np.concatenate(pieces), voice.rate), media_type="audio/wav")

    # English — Piper. API differs between generations: 1.3+ has
    # synthesize_wav(text, wav); older versions stream via synthesize(text).
    piper_voice = EN_VOICES[voice_key]
    out = io.BytesIO()
    with wave.open(out, "wb") as wav_file:
        if hasattr(piper_voice, "synthesize_wav"):
            piper_voice.synthesize_wav(text, wav_file)
        else:
            rate = getattr(getattr(piper_voice, "config", None), "sample_rate", 22050)
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(rate)
            for chunk in piper_voice.synthesize(text):
                data = getattr(chunk, "audio_int16_bytes", None)
                if data is None and isinstance(chunk, (bytes, bytearray)):
                    data = bytes(chunk)
                if data:
                    wav_file.writeframes(data)
    return Response(content=out.getvalue(), media_type="audio/wav")
