"""Neural TTS sidecar for the Bangladesh Betar admin portal (M31).

POST /synthesize {text, language: en|bn, voice: male|female} -> WAV bytes.
Everything runs on onnxruntime — Piper-class lightweight, no PyTorch:
  English — Piper (Ryan / Amy).
  Bangla  — BanglaTTS male / female VITS voices (real Bangladeshi speakers),
            exported to ONNX at build time; tokenization follows the vocab
            JSON generated by Coqui itself during conversion.
"""

import io
import json
import re
import wave

import numpy as np
import onnxruntime
from fastapi import FastAPI, HTTPException
from fastapi.responses import Response
from piper import PiperVoice
from pydantic import BaseModel

app = FastAPI()

EN_VOICES = {
    "male": PiperVoice.load("/models/en_US-ryan-medium.onnx", config_path="/models/en_US-ryan-medium.onnx.json"),
    "female": PiperVoice.load("/models/en_US-amy-medium.onnx", config_path="/models/en_US-amy-medium.onnx.json"),
}


class BanglaVoice:
    """ONNX VITS voice with the tokenizer recipe recorded at conversion time."""

    def __init__(self, onnx_path: str, meta_path: str):
        self.session = onnxruntime.InferenceSession(onnx_path, providers=["CPUExecutionProvider"])
        with open(meta_path, encoding="utf-8") as fh:
            meta = json.load(fh)
        self.table = {c: i for i, c in enumerate(meta["vocab"])}
        self.add_blank = meta["add_blank"]
        self.use_eos_bos = meta["use_eos_bos"]
        self.blank_id = meta["blank_id"]
        self.bos_id = meta["bos_id"]
        self.eos_id = meta["eos_id"]
        self.rate = meta["sample_rate"]
        self.input_names = meta["input_names"]

    def _ids(self, text: str) -> list[int]:
        ids = [self.table[c] for c in text if c in self.table]
        if not ids:
            return []
        if self.add_blank:
            out = [self.blank_id]
            for i in ids:
                out.extend((i, self.blank_id))
            ids = out
        if self.use_eos_bos:
            ids = [self.bos_id, *ids, self.eos_id]
        return ids

    def tts(self, text: str, scales: tuple[float, float, float] = (0.667, 1.0, 0.8)) -> np.ndarray | None:
        ids = self._ids(text)
        if not ids:
            return None
        x = np.array([ids], dtype=np.int64)
        feeds = {}
        for name in self.input_names:
            if name == "input":
                feeds[name] = x
            elif name == "input_lengths":
                feeds[name] = np.array([x.shape[1]], dtype=np.int64)
            elif name == "scales":
                feeds[name] = np.array(list(scales), dtype=np.float32)
        return self.session.run(None, feeds)[0].squeeze().astype(np.float32)


BN_VOICES = {
    "male": BanglaVoice("/models/bn_male.onnx", "/models/bn_male.json"),
    "female": BanglaVoice("/models/bn_female.onnx", "/models/bn_female.json"),
}


class SynthesizeRequest(BaseModel):
    text: str
    language: str  # en | bn
    voice: str = "female"  # male | female
    pace: float | None = None            # Bangla length_scale: >1 slower/clearer (0.8–1.4)
    expressiveness: float | None = None  # Bangla noise_scale: higher livelier (0.4–1.0)


# ---- Bangla prosody -------------------------------------------------------
# Explicit breath structure: a full pause after দাঁড়ি (।) / ? / !, a shorter
# one after commas, and per-sentence expressiveness — questions and
# exclamations get a livelier delivery (higher noise_scale), and the pace
# varies slightly between sentences so long passages don't sound mechanical.
BN_PAUSES = {"।": 0.55, "?": 0.60, "!": 0.55, "": 0.40}
BN_COMMA_PAUSE = 0.22
BN_BASE_NOISE = 0.70          # expressiveness: higher = livelier but slurrier
BN_BASE_PACE = 1.06           # length_scale: >1 = slower, clearer articulation
BN_DURATION_NOISE = 0.66      # noise_w: lower = steadier phoneme durations
BN_MIN_CLAUSE = 18            # don't split at a comma if a side is this short


def bn_sentences(text: str):
    """Sentences with their terminator kept (danda included)."""
    parts = re.split(r"(?<=[।?!\n])\s*", text)
    return [p.strip() for p in parts if p.strip()]


def bn_clauses(sentence: str):
    """Split at commas/semicolons, merging fragments too short to stand alone."""
    raw = [c.strip() for c in re.split(r"(?<=[,;])\s*", sentence) if c.strip()]
    clauses: list[str] = []
    for part in raw:
        if clauses and (len(part) < BN_MIN_CLAUSE or len(clauses[-1]) < BN_MIN_CLAUSE):
            clauses[-1] = f"{clauses[-1]} {part}"
        else:
            clauses.append(part)
    return clauses


def bn_narrate(voice, text: str, pace: float | None = None, expressiveness: float | None = None) -> list:
    pieces: list = []
    silence = lambda seconds: np.zeros(int(voice.rate * seconds), dtype=np.float32)  # noqa: E731

    base_noise = min(1.0, max(0.4, expressiveness)) if expressiveness else BN_BASE_NOISE
    base_pace = min(1.4, max(0.8, pace)) if pace else BN_BASE_PACE

    sentences = []
    for chunk in sentence_chunks(text):          # safety cap for wall-of-text input
        sentences.extend(bn_sentences(chunk))

    for index, sentence in enumerate(sentences):
        terminator = sentence[-1] if sentence and sentence[-1] in "।?!" else ""

        # Expressiveness per sentence type + gentle pace variation.
        noise = base_noise
        length = base_pace + ((index % 3) - 1) * 0.02
        if terminator == "?":
            noise = min(1.0, base_noise + 0.10)
        elif terminator == "!":
            noise, length = min(1.0, base_noise + 0.08), length * 0.97

        clauses = bn_clauses(sentence)
        for clause_index, clause in enumerate(clauses):
            # A fragment without terminal punctuation makes the model rush and
            # swallow the final word — close it with a danda so every piece is
            # articulated as a complete utterance (our own pause follows).
            if clause and clause[-1] not in "।?!,;":
                clause = clause + "।"
            waveform = voice.tts(clause, scales=(noise, length, BN_DURATION_NOISE))
            if waveform is not None and waveform.size:
                pieces.append(waveform)
                if clause_index < len(clauses) - 1:
                    pieces.append(silence(BN_COMMA_PAUSE))

        if pieces:
            pieces.append(silence(BN_PAUSES.get(terminator, BN_PAUSES[""])))

    if pieces and pieces[-1].size and float(np.max(np.abs(pieces[-1]))) == 0.0:
        pieces.pop()                              # no trailing silence at the very end
    return pieces


def sentence_chunks(text: str, limit: int = 400):
    """Split on sentence boundaries (Bangla danda included), pack to <= limit chars."""
    parts = re.split(r"(?<=[।.!?\n])\s+", text)
    buf = ""
    for part in parts:
        part = part.strip()
        if not part:
            continue
        if buf and len(buf) + len(part) + 1 > limit:
            yield buf
            buf = part
        else:
            buf = f"{buf} {part}".strip()
    if buf:
        yield buf


def to_wav_bytes(samples: np.ndarray, rate: int) -> bytes:
    peak = float(np.max(np.abs(samples))) if samples.size else 0.0
    if peak > 1.0:  # VITS output can exceed [-1, 1] slightly — normalise
        samples = samples / peak
    pcm = (np.clip(samples, -1.0, 1.0) * 32767).astype(np.int16)
    out = io.BytesIO()
    with wave.open(out, "wb") as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(rate)
        w.writeframes(pcm.tobytes())
    return out.getvalue()


@app.get("/health")
def health():
    return {"ok": True, "engines": {"en": "piper (ryan/amy)", "bn": "banglatts-onnx (real male/female)"}}


@app.post("/synthesize")
def synthesize(req: SynthesizeRequest):
    text = req.text.strip()
    if not text:
        raise HTTPException(422, "Empty text.")
    voice_key = "male" if req.voice == "male" else "female"

    if req.language == "bn":
        voice = BN_VOICES[voice_key]
        pieces = bn_narrate(voice, text, pace=req.pace, expressiveness=req.expressiveness)
        if not pieces:
            raise HTTPException(422, "Nothing to synthesize.")
        return Response(content=to_wav_bytes(np.concatenate(pieces), voice.rate), media_type="audio/wav")

    # English — Piper. API differs between generations: 1.3+ has
    # synthesize_wav(text, wav); older versions stream via synthesize(text).
    piper_voice = EN_VOICES[voice_key]
    out = io.BytesIO()
    with wave.open(out, "wb") as wav_file:
        if hasattr(piper_voice, "synthesize_wav"):
            piper_voice.synthesize_wav(text, wav_file)
        else:
            rate = getattr(getattr(piper_voice, "config", None), "sample_rate", 22050)
            wav_file.setnchannels(1)
            wav_file.setsampwidth(2)
            wav_file.setframerate(rate)
            for chunk in piper_voice.synthesize(text):
                data = getattr(chunk, "audio_int16_bytes", None)
                if data is None and isinstance(chunk, (bytes, bytearray)):
                    data = bytes(chunk)
                if data:
                    wav_file.writeframes(data)
    return Response(content=out.getvalue(), media_type="audio/wav")
