"""One-time build step: convert the BanglaTTS male/female VITS checkpoints
(bangla-speech-processing, MIT) into Piper-style ONNX models.

Runs in a throwaway Docker stage with the full Coqui/PyTorch stack; the
final image ships only the ONNX files + a tokenizer vocab JSON generated by
Coqui itself (so the slim runtime never re-implements tokenization by
guesswork). Each export is verified by an actual ONNX synthesis before the
build is allowed to succeed.
"""

import json

import numpy as np
import onnxruntime
from TTS.config import load_config
from TTS.tts.models.vits import Vits

SAMPLE = "বাংলাদেশ বেতারে আপনাকে স্বাগতম। এটি একটি পরীক্ষামূলক বাক্য।"


def ids_for(meta, text):
    table = {c: i for i, c in enumerate(meta["vocab"])}
    ids = [table[c] for c in text if c in table]
    assert ids, "sample text produced no known characters"
    if meta["add_blank"]:
        out = [meta["blank_id"]]
        for i in ids:
            out.extend((i, meta["blank_id"]))
        ids = out
    if meta["use_eos_bos"]:
        ids = [meta["bos_id"], *ids, meta["eos_id"]]
    return ids


for name in ("male", "female"):
    config = load_config(f"/dl/bn_{name}_config.json")
    model = Vits.init_from_config(config)
    model.load_checkpoint(config, f"/dl/bn_{name}.pth", eval=True)
    out_onnx = f"/out/bn_{name}.onnx"
    model.export_onnx(output_path=out_onnx, verbose=False)

    chars = model.tokenizer.characters
    meta = {
        "vocab": list(chars.vocab),
        "add_blank": bool(getattr(config, "add_blank", True)),
        "use_eos_bos": bool(getattr(config, "enable_eos_bos_chars", False)),
        "blank_id": int(chars.char_to_id(chars.blank)) if getattr(chars, "blank", None) else 0,
        "bos_id": int(chars.char_to_id(chars.bos)) if getattr(chars, "bos", None) else 0,
        "eos_id": int(chars.char_to_id(chars.eos)) if getattr(chars, "eos", None) else 0,
        "sample_rate": int(config.audio.sample_rate),
    }

    session = onnxruntime.InferenceSession(out_onnx, providers=["CPUExecutionProvider"])
    meta["input_names"] = [i.name for i in session.get_inputs()]
    with open(f"/out/bn_{name}.json", "w", encoding="utf-8") as fh:
        json.dump(meta, fh, ensure_ascii=False)

    # Verify: a real synthesis through the exported graph must produce audio.
    ids = np.array([ids_for(meta, SAMPLE)], dtype=np.int64)
    feeds = {}
    for input_name in meta["input_names"]:
        if input_name == "input":
            feeds[input_name] = ids
        elif input_name == "input_lengths":
            feeds[input_name] = np.array([ids.shape[1]], dtype=np.int64)
        elif input_name == "scales":
            feeds[input_name] = np.array([0.667, 1.0, 0.8], dtype=np.float32)
        else:
            raise SystemExit(f"unexpected ONNX input: {input_name}")
    wav = session.run(None, feeds)[0].squeeze()
    duration = float(wav.shape[-1]) / meta["sample_rate"]
    print(f"{name}: ONNX verified, sample duration {duration:.2f}s")
    assert duration > 1.0, f"{name}: verification synthesis too short"

print("conversion complete")
